유수민 46일차 문제풀이 체크
SolveEveryday/Exercise pull request #152
Opened 2022-11-29 17:10 UTC by sue4869

맞게 한거 같은데 어떤 점에서 틀렸는지 이해가 안가서 올립니다. 
## 로직
1. 우선순위큐로 오름차순으로 정렬
2. 합을 보관하는 큐 생성
3. 합 큐가 비어 있을 경우, 가장 작은 수와 그다음 수의 합을 큐에 넣는다. 
해당 수들은 우선순위큐에서 지운다. result값에 그 합을 더한다. 
4. 합큐와 우선순위큐에서 가장 작은 수를 합한다. 
결과값을 합규에 넣고 result에 더한다. 
5. 4를 우선순위큐가 빌때까지 수행
 
## 복잡도

시간복잡도 O(NlogN)
공간복잡도 O(N)

2022-11-30 00:10 UTC, deepredk requested changes
입력
```
4
5
6
7
8
```

정답
```
52
```

출력
```
55
```

2022-11-30 09:43 UTC, sue4869 commented
합의 결과를 다시 넣어서 정렬이 다시 되어야 하는 군여!! 로직이 잘못되었네여 반례 감사합니다!!!
@deepredk

2022-11-30 14:09 UTC, jhd7130 approved these changes
하 저부분에서 생각이 막혀가지고 아주 아까운 문제였어요 진짜...

2022-12-01 06:47 UTC, deepredk approved these changes
👍

2022-12-01 07:01 UTC, sue4869 commented
@HanHyunsoo 확인해주세용!

2022-12-01 07:02 UTC, HanHyunsoo approved these changes
고생하셨습니다 늦게봐서 죄송해요 ㅠㅠ

2022-12-01 07:06 UTC, merged