정희두 52일차 문제풀이 실패
SolveEveryday/Exercise pull request #170
Opened 2022-12-05 15:32 UTC by jhd7130

## 로직

### 사용한 자료구조와 이유
Call Stack입니다. 재귀는 쓰레드의 Stack 공간을 사용합니다. 

### 로직에 대한 직관적인 설명
 1.  사분면의 가장 왼쪽 위의 지점에서 탐색을 시작합니다.
 2. 0,0일 경우 두번째 if문에 걸리게되고 0 ~ size의 범위이기 때문에 사분면의 모든 함수가 호출됩니다. 2개의 stack이 쌓였습니다. 
 3. 각각의 사분면 함수들은 자신의 범위에 해당 목적 point가 존재하는지 확인합니다.
 4. 자신의 범위에 point가 있는 면적만 다시 함수를 호출합니다.
 5. 없다면 숫자 카운트하고 맙니다. 
 6. 만약 목적 포인트와 x,y가 맞는 지점에는 ans를 출력합니다. 

### 로직을 위와 같이 짠 계기&이유
재귀를 이용한 분할 정복 방식으로 작성했습니다. 해당 문제는 틀려서 이 로직을 선택한 이유를 설명합니다.
분할정복 방식의 가장 적절한 방식이라고 생각했습니다. 
전체를 4분면으로 나누 4분면 중에 목적 point가 있는 곳만 다시 분할정복하는 방식이 가장 깔끔하고 적절하다고 판단되었습니다.

## 복잡도
시간복잡도 O(logN)
공간복잡도 O(logN)

분할정복 방식으로 모든 사분면을 방문하지 않고 절반이된 영역들만 방문합니다. 따라서 시간복잡도와 공간복잡도는 logN이 됩니다.

## 채점 결과
실패했습니다.

2022-12-05 17:18 UTC, deepredk requested changes
복잡도를 O(log(size))랑 헷갈리신 것 같습니다
문제에서 주어진 N을 N으로 둔다면 O(N)이 맞아요!

2022-12-06 05:15 UTC, sue4869 approved these changes
👍

2022-12-07 15:22 UTC, jhd7130 reviewed
@deepredk @HanHyunsoo 
네 수정했습니다 감사합니다!

2022-12-08 14:09 UTC, deepredk approved these changes

2022-12-09 11:10 UTC, HanHyunsoo approved these changes

2022-12-09 19:04 UTC, merged