유수민 52일차 문제풀이 실패
SolveEveryday/Exercise pull request #172
Opened 2022-12-05 18:30 UTC by sue4869

## 로직

### 사용한 자료구조와 이유
반복적으로 몇사분면으로 위치하는 가에 대한 로직이 필요했으므로 재귀를 사용해야 했으며, 또한 나눠서 찾는 것이므로 분할 정복에 해당하는 것이라고 생각했다. 

### 로직에 대한 직관적인 설명
1. 재귀함수에 y,x,size 값이 들어온다. 여기서 y,x는 현재 탐색하고자 하는 사분면의 가장 왼쪽 위 좌표이며, size는 현재 사분면의 크기이다
2. 찾고자 하는 좌표 값 r,c가 현재 사분면 내에 존재한다면 현재 사분면을 다시 4등분하여, 현재 4분면의 1,2,3,4 분면 각각의 재귀함수를 호출한다
3. 만약 r,c가 현재 사분면 내에 존재하지 않다면 현재 사분면을 탐색할 필요가 없으므로 ans에 현재 사분면의 크기 size^2을 더해준 후 return 해준다
4. 그렇게 호출 되면서 y,x값이 r,c값과 일치하면 최종적으로 답을 출력하고 return 해준다.
### 로직을 위와 같이 짠 계기&이유
재귀와 분할 정복을 처음에 생각하긴 했었다. 주어진 x,y가 몇사분면에 위치하는가부터 찾아야 하는 지는 알았는데, 이것을 로직상으로 풀어나가질 못하였다. 

## 복잡도

시간복잡도 O(2^N)
공간복잡도 O(2^N)

찾아보니 모든 사분면을 방문해서 탐색하는 것이 아니라 우선적으로 어디 사분면에 위치하는지 사이즈를 쪼개면서 탐색하는 것이므로 O(N)이라고 하는데 사실 아직 왜 O(N)일지 이해가 가질 않는다. O(2^N)이 아닌것인가? n이 2일때 4개로 나눠서 탐색하니까 말이다. 공간복잡도도 호출한 것에 따라가니 O(2^N)이 아닌 것일까? 하지만 만약 시간복잡도가 O(N)이라면, 호출한 빈도기 때문에 시간복잡도를 따라가서 공간복잡도도 O(N)이라고 생각한다. 우선적으로 시간복잡도부터 이해가 가야 할듯 싶다. 
![image](https://user-images.githubusercontent.com/68679529/205713616-55560c85-f293-4e53-b278-7e441947c6c3.png)

2022-12-06 00:33 UTC, HanHyunsoo approved these changes
분할 정복.. 너무 어려운것 같습니다 고생하셨습니다

2022-12-06 02:44 UTC, deepredk approved these changes
시간복잡도가 정확히는 O(log2(size))인데
size는 2^N입니다
log2(2^N) = N이기 때문에 O(N)입니다

2022-12-06 02:44 UTC, deepredk requested changes
아 실수로 Approve로 체크했습니다

2022-12-06 05:16 UTC, sue4869 commented
오오오 자세한 설명 감사합니다 아무리 고민해도 모르겠더라구요 이제 이해가 되었어요! @deepredk

2022-12-06 09:12 UTC, deepredk approved these changes
👍👍👍🙂🙂

2022-12-07 06:06 UTC, sue4869 commented
@jhd7130 희두님 확인해주세용

2022-12-09 09:18 UTC, jhd7130 approved these changes

2022-12-10 06:52 UTC, merged