한현수 53일차 문제 풀이 실패
SolveEveryday/Exercise pull request #173
Opened 2022-12-06 01:08 UTC by HanHyunsoo

## 로직

### 사용한 자료구조와 이유

가장 작은 단위까지 봐야하기 때문에 재귀를 사용했습니다.

### 로직에 대한 직관적인 설명

1. A에서 B로 이동하는 함수를 재귀호출하여 이동해야할 원판이 1개면 A -> B로 이동한 것을 출력한뒤 함수를 리턴한다.(멈춘다.)
2. 원판이 1개일 때 A -> B로 이동한 함수가 닫히면 이전 단계의 재귀로 돌아간다(원판이 2개 일 때) 그러면 1개의 원판이 A -> C로 이동되므로 이 것을 출력.
3. B -> C로 이동하도록 다시 재귀호출

### 로직을 위와 같이 짠 계기&이유

![하노이 탑 예제](https://upload.wikimedia.org/wikipedia/commons/6/60/Tower_of_Hanoi_4.gif?20050322192703)

#### 하노이 탑의 규칙

1. 한 번에 한개의 원판만 옮길 수 있다.
2. 가장 위에 있는 원판만 이동할 수 있다.
3. 큰 원판이 작은 원판 위에 있어서는 안 된다.

1. 가장 큰 원판을 C 로 옮기기 위해서는 n-1 개의 원판이 A -> B로 이동된다.
2. 그리고 A 에 있는 가장 큰 원판이 C 로 이동.
3. B 에 있는 (n-1)개의 원판을 C 로 이동한다.

위 규칙을 지켜서 로직을 짜면 다음과 같다. 이 부분을 재귀적으로 구현하면 됩니다.

## 복잡도

재귀 함수를 호출하면 총 2^N - 1번 호출 됩니다.

시간복잡도 - O(2^N)
공간복잡도 - O(2^N)

## 채점 결과

<img width="1154" alt="스크린샷 2022-12-06 오전 10 08 15" src="https://user-images.githubusercontent.com/37373826/205781063-8c5a5d3d-bd38-4e27-9574-4b491dc4cc4a.png">

2022-12-06 02:42 UTC, deepredk requested changes
실패인건가요 성공인건가요?

2022-12-06 03:18 UTC, HanHyunsoo commented
@deepredk 왜 실패라고 적었을까요... ㅋㅋㅋㅋㅋㅋㅋ 수정했습니다

2022-12-06 04:17 UTC, deepredk approved these changes
ㅋㅋㅋㅋ👍

2022-12-06 04:20 UTC, deepredk commented
어 근데 3^(N-1)번이지 않나요?

2022-12-07 03:10 UTC, deepredk commented
2가 맞는거같습니다
재귀호출 중 하나는 바로 return 되는거였죠 참

2022-12-07 06:07 UTC, sue4869 approved these changes
👍

2022-12-09 09:18 UTC, jhd7130 approved these changes

2022-12-09 09:18 UTC, merged