정희두 60일차 문제풀이 실패
SolveEveryday/Exercise pull request #204
Opened 2022-12-13 17:35 UTC by jhd7130

## 로직

### 사용한 자료구조와 이유
[제것]
숫자의 조합결과값을 받기 위한 Set
전제 숫자와 임시 조합을 담기위한 Array(=Vector)

### 로직에 대한 직관적인 설명
1. 초기화 합니다.
2. 재귀를 시작합니다.
4. tmp에 들어가는 사이즈가 K가 될때 까지 반복하고 다음 수들을 번갈아 끼워가면서 반복합니다.
5. Tmp의 길이가 K가 되었을때 중복이 없게 set에 해당 조합의 합을 저장합니다.
6. 갯수를 출력합니다. 

### 로직을 위와 같이 짠 계기&이유
다들 dfs방식으로 푼 것 같았습니다. 사실 이걸 왜 굳이 dfs 방식으로 불어야하는지 잘 모르겠어서. 재귀 조합 방식이면 될 것 같은데 이걸 왜 방문 처리를 해줘야하는 식으로 풀어야하는지 잘 이해하지 못하겠습니다. 

## 복잡도

시간복잡도 O(2^N)
매 재귀마다 2개의 함수를 호출 하기 때문에

공간복잡도 O(2^N)
재귀 호출 횟수만큼 필요

## 채점 결과
실패했습니다.

2022-12-14 03:51 UTC, deepredk requested changes
희두님 혹시 이때까지 오답코드 그대로 올리신건가요?? 백준에 돌려봤더니 런타임 에러가 나네요
모범답안 코드 따로 구글링 같은걸로 찾으셔서 그걸 해석하고 모범답안 코드를 올리셔야돼요 해석도 모범답안 기준으로 하셔야되고요

2022-12-14 03:56 UTC, deepredk commented
그리고 재귀 조합쪽은 잘 모르겠어서 제가 뭐라 말씀을 드리기가 어렵네요ㅠ
확실하게 말씀드릴 수 있는 부분만 말씀드리자면 ysm, kjh, hhs 코드는 DFS와 전혀 관계가 없습니다

2022-12-14 04:05 UTC, HanHyunsoo commented
@deepredk 백트래킹이 dfs를 이용해 필요없는 유망 노드를 가지치기하는거기때문에 dfs를 사용했단 말은 맞는거같아요.

bool 배열을 이용한 것도 유망 노드를 찾기위해서 순서를 판단하기 위한 백트래킹 방법중 하나이구요

2022-12-14 04:10 UTC, deepredk commented
@HanHyunsoo 
아 공유 감사합니다
그래프와 관련이 있어야만 DFS, BFS에 해당하는지 알고 있었네요

2022-12-14 04:17 UTC, HanHyunsoo commented
@deepredk 브루트포스 알고리즘이란게 모든 경우의 수를 찾는 알고리즘인데

선형(완전 탐색), 비선형(dfs, bfs) 두개로 나뉘기 때문이에요

이 문제같은 경우도 각 값들을 하나의 노드로 보고 비선형 구조로 푸는게 시간면에서 더 빠르고 코드도 간결하기 때문에 dfs 방식으로 푼 것 같습니당 ㅎㅎ..

@jhd7130 dfs에서 조건을 추가해서 가지치기 한것이 백트래킹인데 이 부분을 좀더 공부하시면 왜 bool을 썼는지 이해가 빨리되실거에요!! 아니면 디버깅해서 함수가 멈추는때 bool배열의 형태를 보셔두되구요

2022-12-14 05:14 UTC, jhd7130 commented
@deepredk 
정답코드는 구글링 후에 나온 것들을 가지고 답안을 썼습니다. 제 코드는 답안 코드와 비슷하지만 배열오 체킹하는 방식이 없습니다. 런타임에러는 제가 백준에서 돌려보지 않았습니다. 블로그 글이라 당연히 맞을 줄 알고 분석만 했네요 ㅠㅠ

재귀를 통해서 결과값들을 string으로 더해 값을 만들었고 set을 통해 중복을 제거했기 때문에 순열을 쓰지 않더라도 중복되는 값을 제거할 수 있을 거라고 생각했습니다. 

조합과 순열의 차이 설명해주신거 이해에 도움이 많이 됩니다. 제가 질문 드렸던 문제 해석에 대한 궁금증이 풀렸습니다. 

@HanHyunsoo 
팁 감사합니다! 제가 조금 더 고민해보고 올리도록 할게요

2022-12-16 04:01 UTC, deepredk approved these changes
아 여태 Approve 안드렸네요 Approve합니다!

2022-12-16 04:02 UTC, deepredk commented
@HanHyunsoo

2022-12-16 06:12 UTC, sue4869 approved these changes
👍

2022-12-18 10:52 UTC, HanHyunsoo approved these changes

2022-12-18 11:45 UTC, merged