유수민 64일차 문제풀이
SolveEveryday/Exercise pull request #218
Opened 2022-12-17 12:57 UTC by sue4869

## 로직

### 로직에 대한 직관적인 설명
e,s,m 각각의 경계가 넘었을 경우 1로 만들고 입력된 값과 각각 일치시 year를 출력한다. 

### 로직을 위와 같이 짠 계기&이유
문제에서 표현한 그대로 구현

## 복잡도
N = year
시간복잡도 O(N) - year만큼 반복함.
공간복잡도 O(1)

시간복잡도의 기준을 year로 잡아도 되는 것인지 모르겠음

## 채점 결과
![image](https://user-images.githubusercontent.com/68679529/208242963-7518cd75-883b-4011-9641-181f1b54bf12.png)

문제가 엄청 쉬운 김에 자바도 시작!

2022-12-18 11:39 UTC, HanHyunsoo approved these changes
👍

2022-12-18 11:48 UTC, jhd7130 approved these changes

2022-12-18 15:08 UTC, deepredk requested changes
year은 출력(결과)이지 입력이 아니기때문에
시간복잡도의 기준으로 사용하긴 부적절한 것 같습니다

2022-12-19 09:47 UTC, sue4869 commented
혹시 왜 E*S*M 값이 시간복잡도인지 자세히 설명해주실 수 있으실까요?? @deepredk

2022-12-19 10:19 UTC, deepredk commented
@sue4869 수민님 멘션받고 다시 생각해보니 O(ESM)도 아닌 것 같습니다
1 2 3에 대해 5266이 나오는게 이상하니까요

2022-12-19 10:20 UTC, deepredk approved these changes
일단 Approve 해두겠습니다

2022-12-19 10:21 UTC, deepredk commented
@HanHyunsoo @jhd7130 
혹시 어떤 과정으로 O(ESM)을 시간복잡도로 산정하게 되셨나요?

저도 ESM인 줄 알았는데
<img width="940" alt="CleanShot 2022-12-19 at 19 20 49@2x" src="https://user-images.githubusercontent.com/33937365/208403417-36db31af-8f91-4503-81aa-2c7d5a800d52.png">
이 예제를 보고 더 생각해보니 시간복잡도 산정을 아예 할 수가 없어보이네요

2022-12-20 15:12 UTC, merged