한현수 64일차 문제 풀이
SolveEveryday/Exercise pull request #220
Opened 2022-12-18 10:57 UTC by HanHyunsoo

## 로직

### 로직에 대한 직관적인 설명

1. E, S, M을 입력받는다. 년도를 저장할 answer 변수를 1로초기화하여 선언한다.
2. E, S, M이 각각 1이 될때까지 다음을 반복한다.
    2-1. answer를 1 더하는 동시에 E, S, M을 각각 1씩뺀다.
    2-2. E, S, M이 각각 1보다 작으면 15, 28, 19로 초기화한다.
3. answer를 출력한다.

### 로직을 위와 같이 짠 계기&이유

값이 넘어서면 초기화를 해줘야 하기 때문에 반복을 썼음.

## 복잡도

시간복잡도 - O(N)
공간복잡도 - O(1)

여기서 N은 answer를 의미한다.

## 채점 결과

<img width="1149" alt="스크린샷 2022-12-18 오후 7 57 07" src="https://user-images.githubusercontent.com/37373826/208294510-c9880cd1-218a-4d86-875e-9f9a910ea021.png">

2022-12-18 11:48 UTC, jhd7130 approved these changes

2022-12-18 15:10 UTC, deepredk requested changes
N을 어떤걸로 두셨나요?

2022-12-19 00:58 UTC, HanHyunsoo commented
@deepredk N이 answer로 시간복잡도를 생각했는데 곰곰히 생각해보니까 answer는 E * S * M의 시간복잡도를 따르네요.. 수정했습니다!!

2022-12-19 02:57 UTC, deepredk approved these changes
👍

2022-12-19 09:47 UTC, sue4869 approved these changes
👍

2022-12-20 00:17 UTC, merged