정희두 68일차 문제풀이 실패
SolveEveryday/Exercise pull request #234
Opened 2022-12-21 14:55 UTC by jhd7130

## 로직

### 사용한 자료구조와 이유
재귀

### 로직에 대한 직관적인 설명
n ==0 일 때 즉 3의 0승을 기저사례로 시작합니다.
재귀의 결과를 반환하고 
재귀로 넘긴 제곱수만큼 빈 공백을 출력합니다.
위의 재귀와 같은 재귀의 결과를 반환합니다.

### 로직을 위와 같이 짠 계기&이유
![IMG_B95C524EC6D1-1](https://user-images.githubusercontent.com/78134917/208931825-67bfca8a-ad73-418f-b6f1-4b26ab63f652.jpeg)

제 분석은 위와 같습니다.
재귀로 앞 뒤 두구간을 나누고 재귀로 반복합니다. 가운데 구간은 공백을 출력합니다. 가장 작은 구간으로 가서 -부터 재귀함수의 결과로 세등분 중 앞 뒤 두 구간을 쌓아 올립니다. 

## 복잡도

시간복잡도 O(N + N + N ...) 
공간복잡도 O(스택의 생성 수 만큼)

## 채점 결과
실패 했습니다.

2022-12-21 23:29 UTC, deepredk requested changes
복잡도 산정이 명확하게 되지 않은 것 같습니다

2022-12-24 15:30 UTC, jhd7130 commented
@deepredk 
수정했습니다.

2022-12-25 00:10 UTC, deepredk approved these changes
👍

2022-12-25 04:36 UTC, jhd7130 commented
@sue4869 @HanHyunsoo 
확인 부탁드려요!

2022-12-25 09:19 UTC, HanHyunsoo approved these changes

2022-12-26 07:26 UTC, sue4869 approved these changes
👍

2022-12-26 07:30 UTC, merged