68일차 유수민 문제 풀이
SolveEveryday/Exercise pull request #235
Opened 2022-12-21 16:13 UTC by sue4869

## 로직
C++은 성공했으나,
자바의 경우, 다른 사람의 풀이를 참고 하였습니다. 
1) 입력이 끝나는 경우 판단 -> while문의 조건
2) 제곱 : Math.pow(밑,지수)
3) 문자열 : StringBuilder v = new StringBuilder();
4) 문자열에 문자 붙이기 : v. append()
5) 해당 인덱스에 해당하는 곳에 문자 바꾸기: v.setCharAt(인덱스,바꿀문자)

### 사용한 자료구조와 이유
재귀 - 3등분하고 2번째 공간을 빈문자열로 만드는 행위가 반복되므로

### 로직에 대한 직관적인 설명
입력받은 숫자만큼 문자열에 -을 채워준후, 3으로 나누었을때 2번째 공간에 해당하는 인덱스 칸을 다시 빈문자열로 채운다. 나머지 첫번째, 세번째 공간을 방금 행한 과정을 반복한다. 
### 로직을 위와 같이 짠 계기&이유
문제에서 말한 그대로 짰다. 

## 복잡도

시간복잡도 O(N) 
->2^logN이므로 N이다. 재귀를 2번씩 부르고 27 -> 9 -> 3 ->1이므로 logN이다. 
공간복잡도 O(3^N); 

## 채점 결과
![image](https://user-images.githubusercontent.com/68679529/208951234-ab41d1b5-bf9e-4ed3-9553-f03ebd229cb9.png)

2022-12-21 23:26 UTC, deepredk requested changes
2^log_3(N)이지 않나요??

2022-12-22 04:11 UTC, sue4869 commented
아아 그러네여 맞아요 log_3(N) 이네요 log2(N)이 아니라ㅎㅎㅎ 정정하겠습니당

2022-12-22 12:56 UTC, HanHyunsoo approved these changes
👍

2022-12-23 03:57 UTC, deepredk approved these changes
👍

2022-12-23 16:23 UTC, sue4869 commented
@jhd7130 확인해주세용

2022-12-23 16:24 UTC, jhd7130 approved these changes

2022-12-24 15:10 UTC, merged