정희두 69일차 문제풀이 실패
SolveEveryday/Exercise pull request #237
Opened 2022-12-22 16:21 UTC by jhd7130

## 로직

### 사용한 자료구조와 이유
2차원 배열을 이용하였습니다.

### 로직에 대한 직관적인 설명
1. 1  * 1이 될때가 기저사례
2. 분할 정복 방식으로 9개의 등분을 나눕니다.
3. 각 작은 사각형이 모두 같은 수로 되어 있는지 확인합니다. 
4. 맞다면 해당 사각형의 첫번째 요소의 값의 개수를 올립니다.
5. 그렇지 않다면 다시 9등분을 하며 각 등분의 시작 요소에서 다시 재귀를 들어갑니다.
결과를 출력합니다. 

### 로직을 위와 같이 짠 계기&이유
<img width="485" alt="스크린샷 2022-12-23 오전 1 18 01" src="https://user-images.githubusercontent.com/78134917/209177027-a9cc6289-6a7a-4df3-82fc-9b21107ac3be.png">

사각형의 요소를 확인하고 다른게 하나라도 있다면 9등분해야하는 것 글에 나온 방식대로 풀면 된다고 해석했습니다. 
그래서 가장 작은 요소인 1 *1짜리 사각형이 되었을 때 부터 사각형 하나씩 체크해 나갑니다. 

## 복잡도

시간복잡도 O(N^3)
N을 3씩 나눠가면서 9번씩 소환합니다.
공간복잡도 O(N)

## 채점 결과
실패했습니다.

2022-12-23 03:59 UTC, deepredk requested changes
<img width="380" alt="CleanShot 2022-12-23 at 12 58 28@2x" src="https://user-images.githubusercontent.com/33937365/209268258-48057dd5-3e1e-4c3f-b9ce-447f2d894713.png">

N이 최대 3^7까지 들어오는데
N^3이라면 100억대의 반복횟수가 나와서 시간초과가 날 수 밖에 없습니다

2022-12-24 01:07 UTC, deepredk commented
@HanHyunsoo @sue4869

> 2. 어제 올라온 PR의 로직 설명을 읽어보고 Request changes 또는 Approve를 선택하여 리뷰한다.

규칙상 리뷰는 그제가 아닌 어제꺼까지 전부 처리해주셔야 돼요!
그래야 뭔가 피드백(Change Requested)이 왔을때 여유롭게 그 다음 날까지 반영하고 Merge할 수 있으니까요

2022-12-24 15:11 UTC, sue4869 approved these changes
👍

2022-12-25 04:37 UTC, jhd7130 commented
@deepredk @HanHyunsoo 
확인부탁드려요

2022-12-25 09:19 UTC, HanHyunsoo approved these changes
👍

2022-12-26 07:32 UTC, deepredk approved these changes
👍

2022-12-26 07:35 UTC, merged