유수민 69일차 문제풀이
SolveEveryday/Exercise pull request #238
Opened 2022-12-22 17:00 UTC by sue4869

## 로직

### 로직에 대한 직관적인 설명
하나의 수로 이루어져 있을때까지 9등분하고 하나의 수로 이루어져 있는 공간의 개수를 센다. 
### 로직을 위와 같이 짠 계기&이유
문제에서 나타난 그대로 구현

## 복잡도

시간복잡도 O(N)
공간복잡도 O(N)

9개 호출이므로 지수는 9, 1개 -> 9개 -> 27개 이므로 log_9(N) 따라서, 9^log_9(N)가 아닐까 예상합니다. 

## 채점 결과
![image](https://user-images.githubusercontent.com/68679529/209187465-11eaabef-cbfb-4867-bb64-366af031d53f.png)

2022-12-23 04:04 UTC, deepredk requested changes
1 -> 9 -> 27은 3^N이고 역순은 log_3(N)입니다

2022-12-23 16:25 UTC, sue4869 commented
오옹 그러네여 감사합니다!

2022-12-24 01:07 UTC, deepredk commented
@HanHyunsoo @jhd7130

> 2. 어제 올라온 PR의 로직 설명을 읽어보고 Request changes 또는 Approve를 선택하여 리뷰한다.

규칙상 리뷰는 그제가 아닌 어제꺼까지 전부 처리해주셔야 돼요!
그래야 뭔가 피드백(Change Requested)이 왔을때 여유롭게 그 다음 날까지 반영하고 Merge할 수 있으니까요

2022-12-24 01:09 UTC, deepredk commented
@sue4869
제 PR 시간복잡도 계산에서 이해 안되시는 부분 말씀해주시면 어떤 설명드려야 할지 알기 쉬울 것 같슴다

2022-12-24 15:13 UTC, sue4869 commented
1개 -> 9개 -> 27개로 분기를 3^N으로 했는데 진홍님은 log_3(N)으로 하셨더라구여 그걸 이해를 못했어요 @deepredk

2022-12-25 00:08 UTC, deepredk commented
@sue4869
어떤게 1->9->27인거에요?? 27->9->1반대 아닌가요

2022-12-25 09:20 UTC, HanHyunsoo approved these changes
👍

2022-12-25 10:16 UTC, sue4869 commented
아 한 박스안에 개수가 27 -> 9 - > 3으로 줄어드네여. 전 박스 개수를 생각했었는데 잘못 생각했었네여

2022-12-25 11:45 UTC, jhd7130 approved these changes

2022-12-26 07:25 UTC, sue4869 commented
@deepredk 확인해주세용

2022-12-26 07:32 UTC, deepredk approved these changes
👍

2022-12-26 08:18 UTC, merged