정희두 70일차 문제풀이
SolveEveryday/Exercise pull request #243
Opened 2022-12-23 17:23 UTC by jhd7130

## 로직

### 사용한 자료구조와 이유
작은 부분의 결과를 담기 위한 배열(3차원)

### 로직에 대한 직관적인 설명
모두 -1일 경우는 서비스를 종료합니다.

그 뒤 문제에 나와 있는 로직과 동일하게 작성합니다.
1. 기저 사례로 1을 리턴합니다.
2. 기존에 결과를 이미 계산하여 가지고 있는 부분인가를 체크 함
3. 있으면 추가 연산없이 해당 값 반환 [디피가 빠른 이유]
4. 없으면 계산하면서 해당 결과를 메모라이제이션 함  

### 로직을 위와 같이 짠 계기&이유
재귀에서 효율성 향상을 할 수 있는 방법은 동적 계획 방식의 알고리즘인데 여기서 메모라이제이션 즉 작은 계산의 결과를 기존에 가지고 있으면서 해당 계산이 필요할 때 마다 저장된 정답이 있다면 제공해주는 방식의 동적 계획 방식을 생각했습니다.

## 복잡도
시간 복잡도는 시간이 너무 늦어 내일 아침에 일어나서 계산하고 수정하겠습니다.

시간복잡도
공간복잡도

## 채점 결과
<img width="1426" alt="스크린샷 2022-12-24 오전 2 17 00" src="https://user-images.githubusercontent.com/78134917/209375274-88a01825-b0a1-4c2d-b5e7-5674945fecf7.png">

2022-12-24 15:15 UTC, sue4869 approved these changes
👍

2022-12-25 00:13 UTC, deepredk requested changes
.

2022-12-25 09:21 UTC, HanHyunsoo approved these changes
👍

2022-12-25 11:46 UTC, jhd7130 commented
@deepredk 
수정했습니다

2022-12-26 09:05 UTC, deepredk approved these changes
👍

2022-12-26 13:11 UTC, merged