한현수 79일차 문제 풀이
SolveEveryday/Exercise pull request #276
Opened 2023-01-02 06:33 UTC by HanHyunsoo

## 로직

### 사용한 자료구조와 이유
배열 - 알파벳들의 개수

### 로직에 대한 직관적인 설명

먼저 입력받은 알파벳들의 개수를 센다.

그런다음 A-Z까지 순회하여 개수의 반 만큼 따로 StringBuilder에 각각 더한다.

이 과정에서 개수가 홀수라면 문자를 따로 저장한다.

StringBuilder에 저장된 값 + 홀수 문자 + StringBuilder에 저장된 값의 반대에서 입력받은 문자와 개수가 같다면 팰린드롬이고 다르면 팰린드롬이 아니다.

### 로직을 위와 같이 짠 계기&이유

대칭이 되려면 각 문자들은 짝수여야한다. 만약 문자가 홀수라면 해당 문자가 가운데에 들어간다는 의미이다.

하지만 이 과정에서 각 문자가 홀수가 여러개라면 대칭이 될 수 없다. 따라서 팰린드롬이 아니다.

## 복잡도

시간복잡도 - O(N): input의 문자 개수
공간복잡도 - O(N): 위와 동일

## 채점 결과

<img width="1157" alt="스크린샷 2023-01-02 오후 3 33 41" src="https://user-images.githubusercontent.com/37373826/210200681-dcf01ff4-90ea-45cd-a0a5-74082e695b1f.png">

2023-01-02 09:25 UTC, deepredk requested changes
코드가 비어있습니다!

2023-01-03 00:19 UTC, HanHyunsoo commented
@deepredk 수정했습니다 감사합니다

2023-01-03 07:05 UTC, deepredk approved these changes
👍

2023-01-03 08:06 UTC, sue4869 approved these changes
👍

2023-01-04 15:34 UTC, jhd7130 approved these changes

2023-01-05 00:10 UTC, merged