신지우 89일차 문제 풀이
SolveEveryday/Exercise pull request #316
Opened 2023-01-14 21:33 UTC by kakjzi

## 로직

### 사용한 자료구조와 이유
linkedList - 모든 정점을 인접 리스트에 저장하기 위해 사용

### 로직에 대한 직관적인 설명
dfs - 친구간의 관계를 완전 탐색하기 위해 사용

### 로직을 위와 같이 짠 계기&이유
A-B-C-D-E  형태를 만족하는 그래프 모양을 찾아야 합니다.
dfs 호출 시 Count 를 세어 총 5번이 될 경우 나머지 dfs를 호출할 필요 없이 위의 형태를 만족하는 것으로 생각하여 바로 정답을 호출

시작하는 정점이 0 이 아닌 다른 정점도 될 수 있으므로 dfs 마지막에 방문 처리를 풀었습니다.

## 복잡도

시간복잡도 O(NM) -  N(정점) 만큼 돌고 연결되어 있는 간선만큼 최대 M번 dfs 호출
공간복잡도 O(N+M) - M(간선) 만큼 인접리스트 공간할당, N(정점) 만큼 visit 배열 공간 할당

## 채점 결과

<img width="876" alt="image" src="https://user-images.githubusercontent.com/82758364/212496718-b3572812-6eac-4733-b8d8-5a59e9a996c9.png">

2023-01-16 13:09 UTC, deepredk requested changes
저는 시간복잡도를 O(N^3)으로 산정했어요

왜냐면

N개의 노드에 대해
해당 노드의 최대 N개의 자식 서브트리를 각각 탐색하고
그 최대 N개의 자식 서브트리를 탐색하는 것에 걸리는 시간복잡도가 O(N)이니까요

어떻게 생각하세요?

O(NM)으로 산정하셨는데
요건 아닐거같은게
'미방문'으로 다시 바꾸는 부분 때문에
노드 A에 대해 모든 자식 노드의 서브트리를 탐색하고
또 그 자식노드가 서브트리를 탐색하고
자식노드의 자식노드가 서브트리를 탐색하고
이런 과정들이 있기때문에 단순 N*M으로는 안 나올 것 같습니다

저도 시간복잡도에 대해 확신이 없어서 의견 좀 나눠보고싶습니다

2023-01-17 04:24 UTC, deepredk approved these changes

2023-01-17 05:10 UTC, sue4869 approved these changes
👍

2023-01-17 13:46 UTC, HanHyunsoo approved these changes
👍

2023-01-18 00:09 UTC, merged