유수민 89일차 문제풀이
SolveEveryday/Exercise pull request #318
Opened 2023-01-15 00:17 UTC by sue4869

## 로직

### 로직에 대한 직관적인 설명
각 노드를 시작점으로 dfs 돌리는데 간선이 4개일때가 친구관계가 성립할때이다. 깊이를 다 뻣어나가서 탐색을 다 하고난후 돌아올때에는(return), 방문배열 표시를 다시 0으로 하여 다른 노드를 통해서도  방문을 할 수 있도록 한다. 
### 로직을 위와 같이 짠 계기&이유
return 후 원상태로 되돌리는게 중요한것 같아 그것에 초첨을 두었다. 

## 복잡도

시간복잡도 O(KN) N:노드 K<=4 간선이 4일때 성공조건이기때문에 4보다 작거나 같은 상수로 각 노드를 돌것이다.
공간복잡도 O(N^2)  alist에 의해

 

## 채점 결과
![image](https://user-images.githubusercontent.com/68679529/212502824-1deaebb0-68e1-4d02-81b1-4125526e2952.png)

2023-01-16 13:07 UTC, deepredk requested changes
저는 시간복잡도를 O(N^3)으로 산정했어요

왜냐면

N개의 노드에 대해
해당 노드의 최대 N개의 자식 서브트리를 각각 탐색하고
그 최대 N개의 자식 서브트리를 탐색하는 것에 걸리는 시간복잡도가 O(N)이니까요

어떻게 생각하세요?

저도 시간복잡도에 대해 확신이 없어서 의견 좀 나눠보고싶습니다

2023-01-17 00:16 UTC, sue4869 commented
전 인접리스트로 구현하였고, dfs하나당 각 정점에 연결되어 있는 간선의 개수만큼 탐색하게 됩니다. 즉, 모든 정점을 다 찾지 않는다는 거죠. 그리고 각 정점에 연결되어 있는 간선의 개수도 일정하지 않기 때문에 dfs 하나의 수행시간은 일정하지 않습니다. 그래서 계산이 다 끝난 시점을 기준으로 시간복잡도를 재야 하는데요. 모든 정점을 한번씩 방문하고, 방문하지 않은 간선을 한번씩 방문하게 되므로, 시간복잡도는 O(N+M)으로 측정하였습니다.

2023-01-17 04:25 UTC, deepredk approved these changes

2023-01-17 11:47 UTC, kakjzi approved these changes
👍🏻

2023-01-17 13:47 UTC, HanHyunsoo approved these changes
👍

2023-01-17 22:32 UTC, merged